global:
  resolve_timeout: 5m

route:
  group_by: ["alertname"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: "webhook"

receivers:
  - name: "webhook"
    webhook_configs:
      - url: "https://webhook.site/your-unique-id" # Replace with your webhook.site URL
        send_resolved: true
